../rtl/Forwarding_unit.v
../rtl/ALU_Pc.v
../rtl/ALU_Branch.v
../rtl/Control_unit.v
../rtl/Data_mem.v
../rtl/Enable_Branch.v
../rtl/Hazard_detect.v
../rtl/IF_ID.v
../rtl/Instruction_mem.v
../rtl/MEM_WB.v
../rtl/mux_WB.v
../rtl/PC.v
../rtl/Reg_file.v
../rtl/ID_EX.v
../rtl/EX_MEM.v
../rtl/mux_2x1_32bit.v
../rtl/mux_3x1_32bit.v
../rtl/ALU.v
../rtl/ALU_Control.v
../rtl/Shift_Left_2.v
../rtl/Sign_extend.v
../rtl/adder_32bit.v
../rtl/Branch_predictor.v
../rtl/BTB.v
../rtl/Top.v
